name: Build Release APK

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK (Unsigned)
        run: ./gradlew assembleRelease

      - name: Upload Unsigned APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned-git
          path: app/build/outputs/apk/release/app-release-unsigned-git.apk
